# Generated by Django 3.1.1 on 2020-11-25 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acluserpermission',
            name='revoke',
        ),
    ]
