# Generated by Django 3.1.1 on 2020-11-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_remove_acluserpermission_revoke'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablelectureset',
            name='lecture_count',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
