# Generated by Django 3.1.1 on 2020-11-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_timetablelectureset_lecture_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='lecture_count',
        ),
        migrations.RemoveField(
            model_name='timetablelectureset',
            name='lecture_count',
        ),
    ]
